__version__ = '0.2.1'
__version_date__ = '1/14/2023'
__author__ = 'James P. Imes'
__email__ = 'jamesimes@gmail.com'
__website__ = 'https://github.com/JamesPImes/og_production_analyzer'
__license__ = 'MIT'
